apiVersion: apps/v1
kind: Deployment
metadata:
  name: candlestick-mysql-app-deploy
  labels:
    name: candlestick-mysql-app-deploy
    app: candlestick-mysql-app
  namespace: candlestick-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candlestick-mysql-app-pod
      app: candlestick-mysql-app

  template:
    metadata:
      name: candlestick-mysql-app-pod
      labels:
        name: candlestick-mysql-app-pod
        app: candlestick-mysql-app
    spec:
      containers:
        - name: candlestick-mysql-app
          imagePullPolicy: Always
          image: sabatiel180/candlestick-mysql-db-app:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "750m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mypassword
          ports:
            - containerPort: 3306
              name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candlestick-rabbitmq-app-deploy
  labels:
    name: candlestick-rabbitmq-app-deploy
    app: candlestick-rabbitmq-app
  namespace: candlestick-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candlestick-rabbitmq-app-pod
      app: candlestick-rabbitmq-app

  template:
    metadata:
      name: candlestick-rabbitmq-app-pod
      labels:
        name: candlestick-rabbitmq-app-pod
        app: candlestick-rabbitmq-app
    spec:
      containers:
        - name: candlestick-rabbitmq-app
          imagePullPolicy: Always
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candlestick-java-api-app-deploy
  labels:
    name: candlestick-java-api-app-deploy
    app: candlestick-java-api-app
  namespace: candlestick-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candlestick-java-api-app-pod
      app: candlestick-java-api-app

  template:
    metadata:
      name: candlestick-java-api-app-pod
      labels:
        name: candlestick-java-api-app-pod
        app: candlestick-java-api-app
    spec:
      containers:
        - name: candlestick-java-api-app
          imagePullPolicy: Always
          image: sabatiel180/candlestick-java-api-app:latest
          env:
            - name: MYSQL_DB
              value: candlestick-mysql-service
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: mypassword
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candlestick-backend-app-deploy
  labels:
    name: candlestick-backend-app-deploy
    app: candlestick-backend-app
  namespace: candlestick-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candlestick-backend-app-pod
      app: candlestick-backend-app

  template:
    metadata:
      name: candlestick-backend-app-pod
      labels:
        name: candlestick-backend-app-pod
        app: candlestick-backend-app
    spec:
      containers:
        - name: candlestick-backend-app
          imagePullPolicy: Always
          image: sabatiel180/candlestick-backend-app:latest
          env:
            - name: RABBITMQ
              value: candlestick-rabbitmq-service
            - name: JAVA_API
              value: candlestick-java-api-service
          ports:
            - containerPort: 3000
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candlestick-frontend-app-deploy
  labels:
    name: candlestick-frontend-app-deploy
    app: candlestick-frontend-app
  namespace: candlestick-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: candlestick-frontend-app-pod
      app: candlestick-frontend-app

  template:
    metadata:
      name: candlestick-frontend-app-pod
      labels:
        name: candlestick-frontend-app-pod
        app: candlestick-frontend-app
    spec:
      containers:
        - name: candlestick-frontend-app
          imagePullPolicy: Always
          image: sabatiel180/candlestick-frontend-app:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RABBITMQ
              value: candlestick-rabbitmq-service
            - name: JAVA_API
              value: candlestick-java-api-service
          ports:
            - containerPort: 3000
              name: http        